### ISSUE TITLE
emacs: the feautre and file name differs

### ISSUE THREAD

**Issue by thomasf** [stapelberg/expanderr#10]
the file name is `expanderr` while the feature is `go-expanderr`. This cuases `(require)` to not work as expected.

```el
(add-to-list 'load-path "~/src/github.com/stapelberg/expanderr")
(require 'go-expanderr) ;; can not find the file to try loading the feature from.
(require 'expanderr) ;; loads the file but does not find the feature because it was not provided
```

**Comment by thomasf** [comment]
I think you should rename the file even though it breaks your currently suggested loading method it is more correct and an easy fix for anyone.. 

While your at it I would suggest moving the lisp code to a `lisp/` subdirectory (it is organized like that in the Emacs sources)

You could probably create a new `expanderr.el` which just loads `lisp/go-expanderr.el` to not break current users.

**Comment by stapelberg** [comment]
Thanks for the report.

> You could probably create a new expanderr.el which just loads lisp/go-expanderr.el to not break current users.

Sounds good. Could you send a pull request for that please?

**Comment by thomasf** [comment]
alright
