### ISSUE TITLE
Consider panicing (or similar) for functions without return values

### ISSUE THREAD

**Issue by stapelberg** [stapelberg/expanderr#15]
Split out of #1 

From @fatih:

```
func foo() {
	// I want to panic here
	bar()

}

func bar() error {
	return errors.New("foo")
}
```

When I call `:GoExpandErr` when my cursor is on `bar()~ inside `foo()` I got this error:

```
2017/12/28 18:04:49 current function returns no values, cannot return error
```

I think if there are no returns, it should default to `panic(err.Error())` or something alike.

**Comment by stapelberg** [comment]
It’s not entirely clear to me whether we should `panic`, `log.Fatal` (which is what I prefer to use), or even make this configurable. Thoughts?

**Comment by fatih** [comment]
> It’s not entirely clear to me whether we should panic, log.Fatal (which is what I prefer to use), or even make this configurable. Thoughts?

Could this be a setting maybe that user can define? I'm not sure how feasible it would be, but worth trying it out.

**Comment by stapelberg** [comment]
I think we could allow users to specify a Go template expression.

This should be a reasonably easy task for newcomers to contribute to the project. Applied the help wanted label.
