### ISSUE TITLE
Feature: read from stdin

### ISSUE THREAD

**Issue by arp242** [stapelberg/expanderr#4]
Right now I need to save my buffer before I can call this tool. It would be nice if this tool was able to read from stdin so I can send data from the editor to there.

**Comment by stapelberg** [comment]
Thanks for your suggestion. I have a few remarks as to why I think it would not be advisable (at least not at this point) to implement this feature:

1. To handle a package which is spread across multiple files, we need to know the filename of what you’re feeding via stdin. Example scenario: you’re trying to expand the errors of a function call within file1.go to a function defined in file2.go. This makes the arguments somewhat awkward: we’d need to specify both a filename and reading from stdin. This strikes me as unusual.

2. For multi-file packages (see point ①), the buffers of the remaining files of the package have to be saved, which makes saving a somewhat asymmetric requirement: you need to save all other buffers, but one buffer can be fed via stdin. Again, this strikes me as unusual.

3. I know there is some ongoing work to make tools compatible with various Go workspace layouts (think Bazel). I’m not sure whether that work would support injecting (a) certain file(s) from stdin, or whether we’d need saved buffers anyway.
