### ISSUE TITLE
Doesn't seem to work with os.Getwd()?

### ISSUE THREAD

**Issue by arp242** [stapelberg/expanderr#6]
```
[~/go/src/a/err]% cat err.go
package err

import "os"

func err() error {
        os.Getwd()
        return nil
}

[~/go/src/a/err]% expanderr err.go:#50
2017/09/21 14:05:53 no *ast.AssignStmt found in path
```

Hmm, okay, so maybe try changing the return value to match `os.Getwd()`?

```
[~/go/src/a/err]% cat err.go
package err

import "os"

func err() (string, error) {
        os.Getwd()
        return "", nil
}

[~/go/src/a/err]% expanderr err.go:#60
2017/09/21 14:07:28 no *ast.AssignStmt found in path
```

Still nothing :-(

Am I calling it wrong? Or is this not supported?

**Comment by stapelberg** [comment]
`os.Getwd` has multiple return values, so you’ll need to either assign the first value to a variable (`wd := os.Getwd()`) or explicitly assign it to underscore: `_ = os.Getwd()`. Afterwards, expansion will work.
